# fabric config

ver:
  python2: 2.7.9
  python3: 3.4.3
  ruby: 2.2.2
  nodejs: 0.12.2

yum_group:
  - Development Tools
  - C Development Tools and Libraries

yum:
  - zsh
  - vim
  - wget
  - curl
  - tree
  - nkf
  - wol
  - tmux
  - R
  - go
  - mercurial
  - gcc-gfortran
  - kernel-devel
  - kernel-headers
  - dkms
  - openmpi
  - openmpi-devel
  - redis
  - mongodb
  - postgresql
  - postgresql-devel
  - sqlite-devel
  - openssl-devel
  - readline-devel
  - libffi-devel
  - bzip2-devel
  - libxml2-devel
  - libxslt-devel
  - libsqlite3x-devel
  - atlas-sse3-devel
  - libpng-devel
  - freetype-devel
  - python3-devel
  - nginx
  - docker-io
  - pandoc

pip:
  - pip
  - fabric
  - pyyaml
  - tornado
  - bottle
  - flake8
  - grip
  - awscli
  - ipython
  - sphinx
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pystan
  - theano
  - pandas
  - pyper
  - selenium
  - mechanize
  - scss

gem:
  - bundler
  - rails
  - compass
  - middleman
  - selenium
  - mechanize

npm:
  - yo

go:
  - github.com/codegangsta/cli
  - github.com/spf13/hugo

brew:
  - zsh
  - vim
  - gcc
  - git
  - gawk
  - gnu-sed
  - nkf
  - wget
  - tree
  - rename
  - jq
  - tmux
  - readline
  - openssl
  - open-mpi
  - gdbm
  - pkg-config
  - sqlite
  - postgresql
  - mariadb
  - mongodb
  - redis
  - rbenv
  - ruby-build
  - pyenv
  - jenkins
  - go
  - mercurial
  - pandoc
