apt:
  - ansible
  - build-essential
  - bzip2
  - cabal-install
  - cmake
  - corkscrew
  - curl
  - dkms
  - docker
  - ethtool
  - expect
  - fabric
  - g++
  - gdebi-core
  - ghc
  - git
  - ImageMagick
  - incron
  - inotify-tools
  - libapparmor1
  - libatlas-base-dev
  - libboost-all-dev
  - libbz2-dev
  - libcairo2-dev
  - libcurl4-openssl-dev
  - libffi-dev
  - libfreetype6-dev
  - libgdbm-dev
  - libgflags-dev
  - libgoogle-glog-dev
  - libhdf5-serial-dev
  - libleveldb-dev
  - liblmdb-dev
  - libmariadb-client-lgpl-dev
  - libopencv-dev
  - libpcap-dev
  - libpng-dev
  - libpng12-dev
  - libpq-dev
  - libprotobuf-dev
  - libreadline6-dev
  - libsnappy-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxslt-dev
  - libzmq3-dev
  - make
  - mercurial
  - nginx
  - nkf
  - nmap
  - nvidia-cuda-toolkit
  - pandoc
  - patch
  - pkg-config
  - postgresql
  - protobuf-compiler
  - python3-dev
  - python-dev
  - python-scipy
  - python-yaml
  - r-base
  - samba
  - scala
  - sqlite3
  - swig
  - time
  - tk-dev
  - tmux
  - tree
  - vim
  - wget
  - zip
  - zlib1g-dev
  - zsh
