cmd: ~/.pyenv/shims/pip
pip:
  - awscli
  - beautifulsoup4
  - bottle
  - csvkit
  - cython
  - fabric
  - feather-format
  - flake8
  - ggplot
  - grip
  - ipykernel
  - ipython
  - jupyter
  - keras
  - matplotlib
  - mechanize
  - mxnet
  - nose
  - numpy
  - pandas
  - pycuda
  - pymc
  - pyper
  - pystan
  - pytoml
  - pyyaml
  - requests
  - requests_oauthlib
  - scikit-learn
  - scipy
  - scss
  - seaborn
  - selenium
  - setuptools
  - six
  - sphinx
  - sympy
  - theano
  - tornado
  - twitter
  - virtualenv
